## Numpy basics 


### Creating multi-dimensional array (ndarray)

In [ ]:
import numpy as np 

In [ ]:
mylist = [1,2,3]
arr1 = np.array(mylist)

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
mylist2 = [[1,2,3],[5,6,8],[8,7,1]]

In [ ]:
arr2 = np.array(mylist2)

In [ ]:
arr2

array([[1, 2, 3],
       [5, 6, 8],
       [8, 7, 1]])

### Two methods 

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr2.dtype

dtype('int32')

In [ ]:
## Convert datatype 
arr2 = arr2.astype(np.float64)

In [ ]:
arr2.dtype

dtype('float64')

### Other functions to create arrays : 


In [ ]:
arr_zero = np.zeros([3,4],dtype = int )

In [ ]:
arr_zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
arr_ones = np.ones([2,5])

In [ ]:
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# empty returns garbage 
arr_garbage = np.empty([3,4])

In [ ]:
arr_garbage 

array([[6.e-322, 0.e+000, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000, 0.e+000]])

## Slicing and indexing 

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
arr[1]

2

In [ ]:
arr[1:3]

array([2, 3])

In [ ]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[3:]

array([4, 5, 6, 7, 8, 9])

In [ ]:
arr[:-3]

array([1, 2, 3, 4, 5, 6])

## Assigning data to ndarray

In [ ]:
arr[3:] = 20 

In [ ]:
arr

array([ 1,  2,  3, 20, 20, 20, 20, 20, 20])

In [ ]:
sub_arr = arr[2:5] 

In [ ]:
sub_arr

array([ 3, 20, 20])

In [ ]:
sub_arr[:] = -3 

In [ ]:
sub_arr

array([-3, -3, -3])

### Boolean Indexing

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [ ]:
data = np.random.randn(7, 4)

In [ ]:
data

array([[ 0.2958862 ,  0.14719788,  1.1340866 , -0.94332092],
       [ 0.06610211, -1.6022483 ,  0.74338018,  1.22372339],
       [ 0.45493814,  0.21894137,  1.10099468, -0.35863144],
       [-0.47641246, -1.04671509,  0.96957883,  0.602887  ],
       [ 0.37274621, -0.26781349,  0.96556576, -1.20649573],
       [ 1.1583365 ,  0.29284569, -0.24546193, -0.15657117],
       [-0.10736187, -0.65790013,  2.14598051,  0.36983691]])

In [ ]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [ ]:
data [names == 'Bob']

array([[ 0.2958862 ,  0.14719788,  1.1340866 , -0.94332092],
       [-0.47641246, -1.04671509,  0.96957883,  0.602887  ]])

### Fancy Indexing 

In [ ]:
# return row 
data[1]

array([ 0.06610211, -1.6022483 ,  0.74338018,  1.22372339])

In [ ]:
# return one element 
data[2][0]

0.45493813868616434

In [ ]:
# return multiple rows : pass no of rows in a list 
data[[2,3]]

array([[ 0.45493814,  0.21894137,  1.10099468, -0.35863144],
       [-0.47641246, -1.04671509,  0.96957883,  0.602887  ]])

In [ ]:
# return multiple rows : pass no of rows in a list in the desired order 
# use negative numbers to return rows from the end 
data[[-5,-1]]

array([[ 0.45493814,  0.21894137,  1.10099468, -0.35863144],
       [-0.10736187, -0.65790013,  2.14598051,  0.36983691]])

In [ ]:
# return multiple elements : retrun element of (1,0) and (2,2) 
data[[1,3],[0,2]]

array([0.06610211, 0.96957883])

### Transposing and swapping axes : 

In [ ]:
data

array([[ 0.2958862 ,  0.14719788,  1.1340866 , -0.94332092],
       [ 0.06610211, -1.6022483 ,  0.74338018,  1.22372339],
       [ 0.45493814,  0.21894137,  1.10099468, -0.35863144],
       [-0.47641246, -1.04671509,  0.96957883,  0.602887  ],
       [ 0.37274621, -0.26781349,  0.96556576, -1.20649573],
       [ 1.1583365 ,  0.29284569, -0.24546193, -0.15657117],
       [-0.10736187, -0.65790013,  2.14598051,  0.36983691]])

In [ ]:
data_transpose = data.T

In [ ]:
data_transpose.shape

(4, 7)

### Universal Functions: Fast Element-wise Array Functions

A universal function, or ufunc, is a function that performs elementwise operations on
data in ndarrays

In [ ]:
arr = np.random.randn(7)

In [ ]:
arr

array([-1.60470579, -1.14226592, -0.30457531,  0.83615738,  0.14625073,
        0.34903602,  0.8361889 ])

In [ ]:
arr**2

array([2.57508066, 1.30477143, 0.09276612, 0.69915917, 0.02138927,
       0.12182614, 0.69921188])

In [ ]:
np.exp(arr)

array([0.20094867, 0.31909516, 0.73743649, 2.30748315, 1.15748636,
       1.41770025, 2.30755588])

In [ ]:
arr2 = np.random.randn(7)

In [ ]:
arr2

array([0.30303138, 0.35490166, 1.67340472, 0.2894084 , 1.86879959,
       1.45077887, 0.34313057])

In [ ]:
np.add(arr,arr2)

array([-1.30167441, -0.78736425,  1.36882941,  1.12556579,  2.01505031,
        1.79981488,  1.17931948])

In [ ]:
np.maximum(arr,arr2)

array([0.30303138, 0.35490166, 1.67340472, 0.83615738, 1.86879959,
       1.45077887, 0.8361889 ])

### Expressing Conditional Logic as Array Operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Take value of xarr if value in cond is true , otherwise take value from yarr 

In [ ]:
result = np.where(cond, xarr, yarr)

In [ ]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4,4)

In [ ]:
arr

array([[ 0.33725363,  0.22508101, -0.66999263, -0.97653947],
       [ 1.47350739,  0.18521535,  0.88975974,  0.40656444],
       [ 0.82253509,  0.58284077,  0.31703182,  0.70850216],
       [ 1.32781019, -0.17069623,  1.29661437, -0.67526661]])

In [ ]:
## second and third params of where may be integers or arrays 
np.where(arr <0 , 0 , arr)

array([[0.33725363, 0.22508101, 0.        , 0.        ],
       [1.47350739, 0.18521535, 0.88975974, 0.40656444],
       [0.82253509, 0.58284077, 0.31703182, 0.70850216],
       [1.32781019, 0.        , 1.29661437, 0.        ]])

### Mathematical and Statistical Methods

sum                Sum of all the elements in the array or along an axis. Zero-length arrays have sum 0.

mean               Arithmetic mean. Zero-length arrays have NaN mean.

std, var           Standard deviation and variance, respectively, with optional degrees of freedom adjustment
                                                                                                (default denominator n).
                
min, max           Minimum and maximum.

argmin, argmax      Indices of minimum and maximum elements, respectively.

cumsum            Cumulative sum of elements starting from 0

cumprod            Cumulative product of elements starting from 1

In [ ]:
arr = np.random.randn(5, 4)

In [ ]:
arr

array([[-0.7868591 ,  0.69595031, -0.69368653, -1.075047  ],
       [ 0.32386747,  1.04655946, -0.78829993,  0.82302134],
       [ 0.40434557, -0.95262094, -0.29671203, -0.61624795],
       [-2.30923   ,  2.22355961,  0.90344893,  0.07177197],
       [-0.59698681, -1.36598993, -2.85764053,  1.77918819]])

In [ ]:
arr.sum()

-4.06760787459139

In [ ]:
arr.mean()

-0.2033803937295695

In [ ]:
# mean across rows 
arr.mean(axis = 1)

array([-0.46491058,  0.35128709, -0.36530884,  0.22238763, -0.76035727])

In [ ]:
## mean across columns 
arr.mean(axis = 0)

array([-0.59297257,  0.3294917 , -0.74657802,  0.19653731])

### Linear Algebra

Linear algebra, like matrix multiplication, decompositions, determinants, and other
square matrix math, is an important part of any array library. Unlike some languages
like MATLAB, multiplying two two-dimensional arrays with * is an element-wise
product instead of a matrix dot product. 

As such, there is a function dot, both an array
method, and a function in the numpy namespace, for matrix multiplication

Function         Description
diag             Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a                   square matrix with zeros on the off-diagonal

dot               Matrix multiplication

trace            Compute the sum of the diagonal elements

det             Compute the matrix determinant

eig             Compute the eigenvalues and eigenvectors of a square matrix

inv              Compute the inverse of a square matrix

pinv            Compute the Moore-Penrose pseudo-inverse inverse of a square matrix

qr             Compute the QR decomposition

svd             Compute the singular value decomposition (SVD)

solve            Solve the linear system Ax = b for x, where A is a square matrix

lstsq            Compute the least-squares solution to y = Xb

In [ ]:
from numpy.linalg import inv 

In [ ]:
mylist = [[1,3],[4,6],[5,3]]
arr = np.array(mylist)

In [ ]:
arr

array([[1, 3],
       [4, 6],
       [5, 3]])

In [ ]:
arr2 = np.array([[2,3],[4,0]])

In [ ]:
arr2

array([[2, 3],
       [4, 0]])

In [ ]:
## muliply two array with suitable dimensions 
array_mul = np.dot(arr,arr2)

In [ ]:
array_mul

array([[14,  3],
       [32, 12],
       [22, 15]])

In [ ]:
np.trace(array_mul)

26

### Random Number Generation

seed             Seed the random number generator

permutation      Return a random permutation of a sequence, or return a permuted range

shuffle           Randomly permute a sequence in place

rand             Draw samples from a uniform distribution

randint          Draw random integers from a given low-to-high range

randn            Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)

binomial         Draw samples a binomial distribution

normal          Draw samples from a normal (Gaussian) distribution

beta            Draw samples from a beta distribution

chisquare          Draw samples from a chi-square distribution

gamma           Draw samples from a gamma distribution

uniform         Draw samples from a uniform [0, 1) distributiona

arange         Return evenly spaced values within a given interval.

linspace       Return evenly spaced numbers over a specified interval.

logspace       Return numbers spaced evenly on a log scale.

In [ ]:
np.random.rand(3,4)

array([[0.15304759, 0.95796038, 0.27016114, 0.94731451],
       [0.74674344, 0.17114906, 0.75037415, 0.27594856],
       [0.77971678, 0.27761905, 0.27346171, 0.26887644]])

In [ ]:
## pass start ,stop and step ( step by default = 1 )
np.arange(2 ,10 )

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## pass start ,stoop and number of points and you will get array of equally spaced points with the specified number 
np.linspace(3,14 ,num =30)

array([ 3.        ,  3.37931034,  3.75862069,  4.13793103,  4.51724138,
        4.89655172,  5.27586207,  5.65517241,  6.03448276,  6.4137931 ,
        6.79310345,  7.17241379,  7.55172414,  7.93103448,  8.31034483,
        8.68965517,  9.06896552,  9.44827586,  9.82758621, 10.20689655,
       10.5862069 , 10.96551724, 11.34482759, 11.72413793, 12.10344828,
       12.48275862, 12.86206897, 13.24137931, 13.62068966, 14.        ])